Repository microsoft/vscode-python-tools-extension-template, pull requests merged in 2023-08, with the labels that each got.

#153 Update README.md
  README.md
Labels: documentation, debt

#154 Update README.md
  README.md
Labels: bug, documentation

#155 Avoid using an empty list as a default argument to a function
  bundled/tool/lsp_server.py
Labels: bug

#159 fix: 'result' referenced before assignment
  bundled/tool/lsp_jsonrpc.py
Labels: bug
